name: Haskell CI

on:
  push:
  pull_request:
  workflow_dispatch:  # For manual triggering
    inputs:
      run:
        description: Run the program to re-enable inactive workflows
        type: boolean
  schedule:
  - cron: "11 13 * * 5"  # 13:11 UTC every Friday

jobs:
  build:
    permissions:
      actions: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.10.7', '9.0.2', '9.2.8', '9.4.8', '9.6.7', '9.8.4', '9.10.3', '9.12.2']
      fail-fast: false

    name: Build with GHC ${{ matrix.ghc }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Haskell setup
      uses: haskell-actions/setup@main
      with:
        ghc-version: ${{ matrix.ghc }}

    - name: Configure
      run: |
        cabal update
        cabal configure --enable-tests --enable-benchmarks -f werror

    - name: Build dependencies
      run: cabal build --only-dependencies

    - name: Build
      run: cabal build all

    - name: Run tests
      run: cabal test all

    - name: Run
      if: matrix.ghc == '9.8.4'
            && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.run))
      run: cabal run -- github-workflows -v reenable -w 10
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
